const dataKendaraan = [
    {
        id: 1,
        id_perusahaan: 1,
        id_pengguna: 2,
        nopol: "D 1234 AB",
        foto: `${process.env.SERVER_URL}/uploads/gambarkendaraan/P1_K1.jpg`,
        bahanbakar: "Bensin",
        jenis: "Mobil",
        merek: "Toyota",
        tipe: "Avanza",
        status: "Aktif",
        jarak_tempuh: 75234,
    },
    {
        id: 2,
        id_perusahaan: 1,
        id_pengguna: 2,
        nopol: "D 5678 CD",
        foto: `${process.env.SERVER_URL}/uploads/gambarkendaraan/P1_K2.jpg`,
        bahanbakar: "Solar",
        jenis: "Mobil",
        merek: "Isuzu",
        tipe: "Panther",
        status: "Nonaktif",
        jarak_tempuh: 120540,
    },
    {
        id: 3,
        id_perusahaan: 1,
        id_pengguna: 2,
        nopol: "B 9876 EF",
        foto: `${process.env.SERVER_URL}/uploads/gambarkendaraan/P1_K3.jpg`,
        bahanbakar: "Bensin",
        jenis: "Motor",
        merek: "Honda",
        tipe: "Vario 150",
        status: "Aktif",
        jarak_tempuh: 38200,
    },
    {
        id: 4,
        id_perusahaan: 1,
        id_pengguna: 7,
        nopol: "E 4567 GH",
        foto: `${process.env.SERVER_URL}/uploads/gambarkendaraan/P1_K4.jpg`,
        bahanbakar: "Listrik",
        jenis: "Mobil",
        merek: "Hyundai",
        tipe: "Ioniq 5",
        status: "Aktif",
        jarak_tempuh: 22800,
    },
    {
        id: 5,
        id_perusahaan: 1,
        id_pengguna: 4,
        nopol: "F 7890 IJ",
        foto: `${process.env.SERVER_URL}/uploads/gambarkendaraan/P1_K5.jpg`,
        bahanbakar: "Bensin",
        jenis: "Motor",
        merek: "Yamaha",
        tipe: "NMAX",
        status: "Nonaktif",
        jarak_tempuh: 49800,
    },
];

module.exports = { dataKendaraan };
