let dataPengguna = [
    {
        id: 1,
        nama: "Rafi Bintang",
        email: "rafibintang26.rb@gmail.com",
        password: "12345678",
        peran: "Owner",
        id_perusahaan: 1,
    },
    {
        id: 2,
        nama: "Ratha",
        email: "ratha@mail.com",
        password: "rathapass",
        peran: "Admin",
        id_perusahaan: 1,
    },
    {
        id: 3,
        nama: "Nadia Wulandari",
        email: "nadia@gmail.com",
        password: "password123",
        peran: "Driver",
        id_perusahaan: 1,
    },
    {
        id: 4,
        nama: "Dio Pratama",
        email: "dio.pratama@yahoo.com",
        password: "dio12345",
        peran: "Driver",
        id_perusahaan: 1,
    },
    {
        id: 5,
        nama: "Salsa Aulia",
        email: "salsa@gmail.com",
        password: "salsa890",
        peran: "Driver",
        id_perusahaan: 1,
    },
    {
        id: 6,
        nama: "Arif Nugroho",
        email: "arifnugroho@gmail.com",
        password: "arif456",
        peran: "Driver",
        id_perusahaan: 1,
    },
    {
        id: 7,
        nama: "Putri Amalia",
        email: "putri.amalia@mail.com",
        password: "putri123",
        peran: "Driver",
        id_perusahaan: 1,
    },
    {
        id: 8,
        nama: "Fikri Ramadhan",
        email: "fikri@ramadhan.co.id",
        password: "fikri2024",
        peran: "Driver",
        id_perusahaan: 1,
    },
    {
        id: 9,
        nama: "Yasmin Zahra",
        email: "yasmin.zahra@mail.com",
        password: "yasminpw",
        peran: "Driver",
        id_perusahaan: 1,
    },
    {
        id: 10,
        nama: "Dimas Anugrah",
        email: "dimas.anugrah@gmail.com",
        password: "dimas123",
        peran: "Driver",
        id_perusahaan: 1,
    },
    {
        id: 11,
        nama: "Andi Kurniawan",
        email: "andi.kurniawan@perusahaan1.com",
        password: "andi123",
        peran: "Driver",
        id_perusahaan: 1,
    },
    {
        id: 12,
        nama: "Lina Maharani",
        email: "lina.maharani@perusahaan1.com",
        password: "lina456",
        peran: "Driver",
        id_perusahaan: 1,
    },
    {
        id: 13,
        nama: "Fajar Hidayat",
        email: "fajar.hidayat@perusahaan1.com",
        password: "fajar789",
        peran: "Driver",
        id_perusahaan: 1,
    },
];

module.exports = { dataPengguna };
