import { kendaraan1, kendaraan2, kendaraan3 } from "../../assets/images";

const dataKendaraan = [
    {
        Nopol: "B 1234 KYZ",
        Foto: kendaraan1,
        JarakTempuh: "1028 KM",
        BahanBakar: "Bensin",
        Jenis: "Mobil",
        Merek: "Mitsubishi",
        Tipe: "Outlander",
        Status: "Aktif",
    },
    {
        Nopol: "D 5678 ABC",
        Foto: kendaraan2,
        JarakTempuh: "25.000 KM",
        BahanBakar: "Solar",
        Jenis: "Truk",
        Merek: "Isuzu",
        Tipe: "Elf",
        Status: "Tidak Aktif",
    },
    {
        Nopol: "F 9876 ZXC",
        Foto: kendaraan3,
        JarakTempuh: "5.120 KM",
        BahanBakar: "Listrik",
        Jenis: "Mobil",
        Merek: "Hyundai",
        Tipe: "Ioniq 5",
        Status: "Aktif",
    },
    {
        Nopol: "D 5678 ABC",
        Foto: kendaraan2,
        JarakTempuh: "25.000 KM",
        BahanBakar: "Solar",
        Jenis: "Truk",
        Merek: "Isuzu",
        Tipe: "Elf",
        Status: "Tidak Aktif",
    },
    {
        Nopol: "F 9876 ZXC",
        Foto: kendaraan3,
        JarakTempuh: "5.120 KM",
        BahanBakar: "Listrik",
        Jenis: "Mobil",
        Merek: "Hyundai",
        Tipe: "Ioniq 5",
        Status: "Aktif",
    },
    {
        Nopol: "D 5678 ABC",
        Foto: kendaraan2,
        JarakTempuh: "25.000 KM",
        BahanBakar: "Solar",
        Jenis: "Truk",
        Merek: "Isuzu",
        Tipe: "Elf",
        Status: "Tidak Aktif",
    },
    {
        Nopol: "F 9876 ZXC",
        Foto: kendaraan3,
        JarakTempuh: "5.120 KM",
        BahanBakar: "Listrik",
        Jenis: "Mobil",
        Merek: "Hyundai",
        Tipe: "Ioniq 5",
        Status: "Aktif",
    },
    {
        Nopol: "D 5678 ABC",
        Foto: kendaraan2,
        JarakTempuh: "25.000 KM",
        BahanBakar: "Solar",
        Jenis: "Truk",
        Merek: "Isuzu",
        Tipe: "Elf",
        Status: "Tidak Aktif",
    },
    {
        Nopol: "F 9876 ZXC",
        Foto: kendaraan3,
        JarakTempuh: "5.120 KM",
        BahanBakar: "Listrik",
        Jenis: "Mobil",
        Merek: "Hyundai",
        Tipe: "Ioniq 5",
        Status: "Aktif",
    },
    {
        Nopol: "F 9876 ZXC",
        Foto: kendaraan3,
        JarakTempuh: "5.120 KM",
        BahanBakar: "Listrik",
        Jenis: "Mobil",
        Merek: "Hyundai",
        Tipe: "Ioniq 5",
        Status: "Aktif",
    },
    {
        Nopol: "F 9876 ZXC",
        Foto: kendaraan3,
        JarakTempuh: "5.120 KM",
        BahanBakar: "Listrik",
        Jenis: "Mobil",
        Merek: "Hyundai",
        Tipe: "Ioniq 5",
        Status: "Aktif",
    },
];

export { dataKendaraan };
