const columnPengguna = [
    { key: "UserID", name: "Id" },
    { key: "Nama", name: "Nama" },
    { key: "Peran", name: "Peran" },
    { key: "Email", name: "Email" },
    { key: "JumKendaraan", name: "Jumlah Kendaraan Terkait" },
];
const dataPengguna = [
    {
        Id: 1,
        Nama: "Rafi Bintang",
        Peran: "Owner",
        Email: "rafi.bintang@example.com",
        KendTerkait: 5,
    },
    {
        Id: 2,
        Nama: "Nadya Kusuma",
        Peran: "Admin",
        Email: "nadya.kusuma@example.com",
        KendTerkait: 2,
    },
    {
        Id: 3,
        Nama: "Fikri Ramadhan",
        Peran: "Mekanik",
        Email: "fikri.ramadhan@example.com",
        KendTerkait: 4,
    },
    {
        Id: 4,
        Nama: "Aulia Rahman",
        Peran: "Supervisor",
        Email: "aulia.rahman@example.com",
        KendTerkait: 1,
    },
    {
        Id: 5,
        Nama: "Dina Melati",
        Peran: "Mekanik",
        Email: "dina.melati@example.com",
        KendTerkait: 3,
    },
    {
        Id: 6,
        Nama: "Bayu Saputra",
        Peran: "Driver",
        Email: "bayu.saputra@example.com",
        KendTerkait: 6,
    },
    {
        Id: 7,
        Nama: "Citra Anggraini",
        Peran: "Admin",
        Email: "citra.anggraini@example.com",
        KendTerkait: 2,
    },
    {
        Id: 8,
        Nama: "Rizky Pratama",
        Peran: "Admin",
        Email: "rizky.pratama@example.com",
        KendTerkait: 7,
    },
    {
        Id: 9,
        Nama: "Sari Wijaya",
        Peran: "Mekanik",
        Email: "sari.wijaya@example.com",
        KendTerkait: 3,
    },
    {
        Id: 10,
        Nama: "Andi Nugroho",
        Peran: "Driver",
        Email: "andi.nugroho@example.com",
        KendTerkait: 4,
    },
    {
        Id: 11,
        Nama: "Lia Marlina",
        Peran: "Admin",
        Email: "lia.marlina@example.com",
        KendTerkait: 1,
    },
    {
        Id: 12,
        Nama: "Fahri Setiawan",
        Peran: "Supervisor",
        Email: "fahri.setiawan@example.com",
        KendTerkait: 5,
    },
    {
        Id: 13,
        Nama: "Yulia Sari",
        Peran: "Mekanik",
        Email: "yulia.sari@example.com",
        KendTerkait: 2,
    },
    {
        Id: 14,
        Nama: "Dedi Hermawan",
        Peran: "Driver",
        Email: "dedi.hermawan@example.com",
        KendTerkait: 6,
    },
    {
        Id: 15,
        Nama: "Putri Larasati",
        Peran: "Admin",
        Email: "putri.larasati@example.com",
        KendTerkait: 8,
    },
    {
        Id: 16,
        Nama: "Tono Wahyudi",
        Peran: "Mekanik",
        Email: "tono.wahyudi@example.com",
        KendTerkait: 3,
    },
    {
        Id: 17,
        Nama: "Maya Puspita",
        Peran: "Admin",
        Email: "maya.puspita@example.com",
        KendTerkait: 2,
    },
    {
        Id: 18,
        Nama: "Galang Mahesa",
        Peran: "Driver",
        Email: "galang.mahesa@example.com",
        KendTerkait: 4,
    },
    {
        Id: 19,
        Nama: "Selvi Amalia",
        Peran: "Supervisor",
        Email: "selvi.amalia@example.com",
        KendTerkait: 1,
    },
    {
        Id: 20,
        Nama: "Iqbal Ramadan",
        Peran: "Admin",
        Email: "iqbal.ramadan@example.com",
        KendTerkait: 9,
    },
];

export { columnPengguna, dataPengguna };
